# .gitlab-ci.yml

# 사용될 Docker 이미지를 정의합니다.
image: openjdk:17


# 파이프라인의 단계를 정의합니다.
stages:
  - build
  - test

# 빌드 단계
build-job:
  stage: build
  script:
    - ./gradlew clean build
  tags:
    - SSAFYRO-backend-CI
  only:
    - develop


# 테스트 단계
test-job:
  stage: test
  script:
    - ./gradlew test
  tags:
    - SSAFYRO-backend-CI
  only:
    - develop