image: openjdk:17

stages:
  - build_and_test

before_script:
  - cd backend
  - chmod +x ./gradlew

build_and_test:
  stage: build_and_test
  script:
    - ./gradlew build
  tags:
    - SSAFYRO-backend-CI
  only:
    - back-end
    - merge_requests